version: '3.5'
services:
  isa_test_task:
    restart: always
    image: jenishtagline/isa-test-task:v1.0.1
    ports:
      - 4000:3434
    volumes:
      - ./:/code
    environment: 
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
  mongo:
    image: mongo
    command: mongod --port 27019
    restart: always
    container_name: mongodb
    ports:
      - 27019:27019
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: